apiVersion: v1
kind: Service
metadata:
  name: spend-control-frontend
  namespace: spend-control
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: spend-control-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
