apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spend-control-secrets-provider
  namespace: spend-control
spec:
  provider: azure
  secretObjects:
    - secretName: spend-control-secrets
      type: Opaque
      data:
        - objectName: spend-control-database-url
          key: DATABASE_URL
        - objectName: spend-control-dev-auth-secret
          key: DEV_AUTH_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "<workload-identity-client-id>"
    keyvaultName: "<key-vault-name>"
    tenantId: "<tenant-id>"
    objects: |
      array:
        - |
          objectName: spend-control-database-url
          objectType: secret
        - |
          objectName: spend-control-dev-auth-secret
          objectType: secret
